### PR TITLE
Add new custom file extension .sel

### PR DESCRIPTION
**Pull request by ZigyTheBird**
Me bad at github

### CODE REVIEW

**Comment by louis1706** [comment]
> Me bad at github

can i know why .sel ?

**Comment by ZigyTheBird** [comment]
.sel is short for Scripted Events Language

**Comment by louis1706** [comment]
> .sel is short for Scripted Events Language

but .sel is already used by other app

**Comment by Elektryk-Andrzej** [comment]
prob not adding

**Pull request closed without merging**
