### PR TITLE
Restructure and add aliases

### PR DESCRIPTION
**Pull request by warden161**

### CODE REVIEW

**Comment by warden161** [comment]
also changed from local references to $(exiled_References)

**Comment by Thundermaker300** [comment]
Looks good so far, I will take a closer look tomorrow. Fix merge conflicts though plz 😃

**Comment by warden161** [comment]
IDK HOW IM NOT GOOD AT GIT

**Comment by warden161** [comment]
Sorry caps lock

**Comment by Thundermaker300** [comment]
If you're using GH desktop just pull the change and it should give you the option to resolve in Visual Studio Code. A lot easier that way.

If that doesn't work, I can fixy it up tomorrow

**Comment by warden161** [comment]
commit soon

**Comment by warden161** [comment]
SHUT UP.... STUPID CONFLICTS...
Anyways, I'm working on another commit. Don't merge

**Comment by warden161** [comment]
Merge 🥺

**Pull request merged**
