### PR TITLE
DynamicPatching change

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Comment by Thundermaker300** [comment]
build errors 🤔

**Comment by louis1706** [comment]
that perfectly normal

**Comment by louis1706** [comment]
Please don't merged this before Exiled 8 because you will be dumb if you do it

**Comment by Elektryk-Andrzej** [comment]
proceedes to merge :trollface:

**Comment by louis1706** [comment]
> proceedes to merge :trollface: 

Make impossible to use ScriptedEvent until next exiled major update :trolling:

**Comment by Thundermaker300** [comment]
Merge conflict

**Pull request merged**
